dist: trusty
sudo: required

os:
  - linux

language: go
go: 1.10.x
install: true

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel
      - rpm2cpio
      - rpm

install:
  - go get -u github.com/bazelbuild/buildifier/buildifier

script:
  # Check for issues with the format of our bazel config files.
  - buildifier -mode=check $(find . -name BUILD -type f)
  - buildifier -mode=check $(find . -name WORKSPACE -type f)
  - buildifier -mode=check $(find . -name '*.bzl' -type f)

  - bazel test //test:*
